const config = 'eyJhcGlLZXkiOiJBSXphU3lBVkVhNGtmdjJIQ2pmQVhRUklVMVlBTkduSThFUmxFMzQiLCJhdXRoRG9tYWluIjoiYXl0bS1jb2RlY29sbGFiLmZpcmViYXNlYXBwLmNvbSIsImRhdGFiYXNlVVJMIjoiaHR0cHM6Ly9heXRtLWNvZGVjb2xsYWItZGVmYXVsdC1ydGRiLmZpcmViYXNlaW8uY29tIiwicHJvamVjdElkIjoiYXl0bS1jb2RlY29sbGFiIiwic3RvcmFnZUJ1Y2tldCI6ImF5dG0tY29kZWNvbGxhYi5hcHBzcG90LmNvbSIsIm1lc3NhZ2luZ1NlbmRlcklkIjoiNjUxMDkzODc3NDM0IiwiYXBwSWQiOiIxOjY1MTA5Mzg3NzQzNDp3ZWI6MTU4YzM1NmVjMWYxYzdhNTBlNTg4MyJ9';

export const FirebaseApp = window.firebase.initializeApp( JSON.parse( atob( config ) ) );
export const FirebaseDB = window.firebase.database();
